---
apiVersion: v1
kind: Deployment
metadata:
  name: jpetstore-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jpet-app
  template:
    metadata:
      labels:
        app: jpet-app
    spec:
      containers:
      - name: chndra/jpetstore
        image: chndra/jpetstore:295
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: jpetstore-svc
spec:
  selector:
    app: jpet-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodeport: 30000
